"""Add missing columns to posts table

Revision ID: 26e54819f124
Revises: 8614ab193cb9
Create Date: 2025-02-05 19:23:14.922529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26e54819f124'
down_revision: Union[str, None] = '8614ab193cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False))
    op.add_column('posts', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('posts', sa.Column('ownner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['ownner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'ownner_id')
    op.drop_column('posts', 'created_at')
    op.drop_column('posts', 'rating')
    op.drop_column('posts', 'published')
    # ### end Alembic commands ###
